---
- name: "Ensure unzip is installed"
  ansible.builtin.package:
    name: "unzip"
    state: present

- name: "Ensure /opt/microsoft directory exists"
  ansible.builtin.file:
    path: "/etc/opt/microsoft"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Ensure /opt/microsoft/mdatp directory exists"
  ansible.builtin.file:
    path: "/etc/opt/microsoft/mdatp"
    recurse: true
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Register mdatp_onboard.json"
  ansible.builtin.stat:
    path: /etc/opt/microsoft/mdatp/mdatp_onboard.json
  register: mdatp_onboard

- name: Extract WindowsDefenderATPOnboardingPackage.zip into /etc/opt/microsoft/mdatp
  ansible.builtin.unarchive:
    src: "{{ mdatp_onboarding_package_location }}"
    dest: "/etc/opt/microsoft/mdatp"
    mode: "0600"
    owner: root
    group: root
  notify:
    - "Enable mdatp"
    - "Restart mdatp"
  when: not mdatp_onboard.stat.exists
