---
- name: "Ensure unzip is installed"
  ansible.builtin.package:
    name: "unzip"
    state: present

- name: "Ensure /opt/microsoft directory exists"
  ansible.builtin.file:
    path: "/etc/opt/microsoft"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Ensure /opt/microsoft/mdatp directory exists"
  ansible.builtin.file:
    path: "/etc/opt/microsoft/mdatp"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Check if mdatp_onboard.json exists"
  ansible.builtin.stat:
    path: /etc/opt/microsoft/mdatp/mdatp_onboard.json
  register: mdatp_onboard

- name: "Extract WindowsDefenderATPOnboardingPackage.zip into /etc/opt/microsoft/mdatp"
  ansible.builtin.unarchive:
    src: "{{ mdatp_onboarding_package_location }}"
    dest: "/etc/opt/microsoft/mdatp"
    mode: "0600"
    owner: root
    group: root
  notify:
    - "Enable mdatp"
    - "Restart mdatp"
  when: not mdatp_onboard.stat.exists

- name: "Apply mdatp_managed.json template"
  ansible.builtin.template:
    src: "mdatp_managed.json.j2"
    dest: "/etc/opt/microsoft/mdatp/mdatp_managed.json"
    mode: "0600"
    owner: root
    group: root
  when: mdatp_managed_json_template
  notify:
    - "Enable mdatp"
    - "Restart mdatp"

- name: "Ensure HTTPS_PROXY environment variable is set in mdatp.service"
  ansible.builtin.lineinfile:
    path: "/usr/lib/systemd/system/mdatp.service"
    regexp: '^Environment="HTTPS_PROXY='
    line: 'Environment="HTTPS_PROXY={{ mdatp_proxy_url }}"'
    insertafter: '#Environment="HTTPS_PROXY=http://address:port"'
  when: mdatp_proxy_url is defined and mdatp_proxy_url
  notify:
    - "Reload systemd"
    - "Restart mdatp"

- name: "Remove HTTPS_PROXY environment variable from mdatp.service if not set"
  ansible.builtin.lineinfile:
    path: "/etc/systemd/system/multi-user.target.wants/mdatp.service"
    regexp: '^Environment="HTTPS_PROXY='
    state: absent
  when: mdatp_proxy_url is not defined or not mdatp_proxy_url
  notify:
    - "Reload systemd"
    - "Restart mdatp"
