---
- name: "Add Microsoft repository"
  when: mdatp_state == "present"
  notify:
    - "Update dnf cache"
    - "Update yum cache"
  block:
    - name: "Ensure Microsoft repository is configured (RedHat Family): {{ mdatp_microsoft_repo_channel }}"
      ansible.builtin.yum_repository:
        name: "microsoft-{{ mdatp_microsoft_repo_channel }}"
        description: "Microsoft Production"
        baseurl: "https://packages.microsoft.com/fedora/{{ ansible_distribution_major_version }}/prod"
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        enabled: true
        state: present
      when: ansible_os_family == "RedHat"

- name: "Remove Microsoft repository"
  when: mdatp_state == "absent"
  notify:
    - "Update dnf cache"
    - "Update yum cache"
  block:
    - name: "Ensure Microsoft repository is removed (RedHat Family): {{ mdatp_microsoft_repo_channel }}"
      ansible.builtin.yum_repository:
        name: "microsoft-{{ mdatp_microsoft_repo_channel }}"
        description: "Microsoft Production"
        baseurl: "https://packages.microsoft.com/fedora/{{ ansible_distribution_major_version }}/prod"
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        enabled: true
        state: absent
      when: ansible_os_family == "RedHat"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
