---
- name: "Add Microsoft repository"
  when: mdatp_state == "present"
  notify:
    - "Update dnf cache"
    - "Update yum cache"
  block:
    - name: "Ensure Microsoft repo key is present (SUSE)"
      ansible.builtin.rpm_key:
        state: present
        key: "https://packages.microsoft.com/keys/microsoft.asc"

    - name: "Ensure Microsoft repository is configured (RedHat Family): {{ mdatp_microsoft_repo_channel }}"
      community.general.zypper_repository:
        repo: "https://packages.microsoft.com/opensuse/{{ ansible_distribution_major_version }}/prod"
        description: "Microsoft Production"
        state: present
        enabled: true
        name: "microsoft-{{ mdatp_microsoft_repo_channel }}"
        priority: 50

- name: "Remove Microsoft repository"
  when: mdatp_state == "absent"
  notify:
    - "Update dnf cache"
    - "Update yum cache"
  block:
    - name: "Ensure Microsoft repository is configured (RedHat Family): {{ mdatp_microsoft_repo_channel }}"
      community.general.zypper_repository:
        repo: "https://packages.microsoft.com/opensuse/{{ ansible_distribution_major_version }}/prod"
        description: "Microsoft Production"
        state: absent
        enabled: true
        name: "microsoft-{{ mdatp_microsoft_repo_channel }}"
        priority: 50

    - name: "Ensure Microsoft repo key is present (SUSE)"
      ansible.builtin.rpm_key:
        state: absent
        key: "https://packages.microsoft.com/keys/microsoft.asc"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
